name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SONASECRET }}
      run: |
        echo "$SUPER_SECRET" > ~/.sbt/1.0/sonatype.sbt 
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test sonatypeBundleRelease
