name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: mkdir -p ~/.gnupg
      name: gpg dir
    - run: mkdir -p ~/.sbt/1.0
      name: sbt dir
      
    - shell: bash
      env:
        SONASECRET: ${{ secrets.SONASECRET }}
      run: |
        echo "$SONASECRET" > ~/.sbt/1.0/sonatype.sbt 
    - shell: bash
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
      run: |
        echo "$GPG_KEY" > ~/.gnupg/pubring.kbx
        
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test publishSigned sonatypeBundleRelease
